SET IDENTITY_INSERT [dbo].[Items] ON
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (1, 1, N'Chicken Supreme', 52.3, N'Tomato sauce, chicken meat, chicken salami, chicken loaf, mushrooms, capsicums, onions, and mozzarella cheese.', N'pizza1.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (2, 1, N'Hawaiian Supreme', 52.3, N'Tomato sauce, chicken meat, chicken loaf, pineapples, and mozzarella cheese.', N'pizza2.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (3, 1, N'Blazing Seafood', 52.3, N'Spicy sweet-sour sauce, tuna, crabsticks, pineapples, capsicums, onions, and mozzarella cheese.', N'pizza3.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (4, 1, N'Triple Chicken', 52.3, N'Thousand island sauce, chicken rolls, chicken meat, chicken salami, mushrooms, tomatoes, onions, and mozzarella cheese.', N'pizza4.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (5, 1, N'Super Supreme', 52.3, N'Tomato sauce, ground beef, beef pepperoni, beef cabanossi, chicken loaf, mushrooms, pineapples, capsicums, olives, onions, and mozzarella cheese.', N'pizza5.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (6, 1, N'Island Supreme', 52.3, N'Thousand island sauce, crabsticks, tuna, pineapples, onions, and mozzarella cheese.', N'pizza6.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (7, 1, N'Beef Pepperoni', 47.9, N'Tomato sauce, beef pepperoni, and mozzarella cheese.', N'pizza7.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (8, 1, N'Aloha Chicken', 47.9, N'Thousand island sauce, chicken rolls, chicken salami, pineapples, and mozzarella cheese.', N'pizza8.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (9, 1, N'Veggie Lover', 47.9, N'Tomato sauce, mushrooms, pineapples, tomatoes, capsicums, onions, and mozzarella cheese.', N'pizza9.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (10, 1, N'Chicken Delight', 47.9, N'BBQ sauce, chicken meat, mushrooms, onions, and mozzarella cheese.', N'pizza10.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (11, 2, N'Coca-Cola Rasa Asli (Can)', 5.5, N'Coca-Cola Rasa Asli (Can)', N'pizza11.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (12, 2, N'Coca-Cola Zero Sugar (Can)', 5.5, N'Coca-Cola Zero Sugar (Can)', N'pizza12.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (13, 2, N'Heaven & Earth Ice Lemon Tea', 5.5, N'Heaven & Earth Ice Lemon Tea', N'pizza13.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (14, 2, N'Sprite (Cup)', 4.9, N'Sprite (Cup)', N'pizza14.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (15, 2, N'Fanta Strawberry (Cup)', 4.9, N'Fanta Strawberry (Cup)', N'pizza15.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (16, 2, N'Minute Maid Orange (Bottled)', 9.7, N'Minute Maid Orange (Bottled)', N'pizza16.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (17, 2, N'Red Bull (Can)', 9.99, N'Red Bull (Can)', N'pizza17.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (18, 2, N'Peach Tea', 4.9, N'Peach Tea', N'pizza18.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (19, 2, N'Lemonade', 4.9, N'Lemonade', N'pizza19.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (20, 2, N'Mineral Water', 3, N'Mineral Water', N'pizza20.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (21, 3, N'WingStreet Krispy Wings (Original)', 53.9, N'Juicy original golden crispy wings served to perfection with light crunchiness.', N'pizza21.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (22, 3, N'WingStreet Krispy Wings (BBQ)', 55.9, N'Juicy original golden crispy wings tossed with barbeque sauce.', N'pizza22.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (23, 3, N'WingStreet Krispy Wings (Tangy Cheese)', 55.9, N'Juicy original golden crispy wings tossed with tangy cheese sauce.', N'pizza23.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (24, 3, N'Garlic Bread', 6.9, N'Garlic and butter spread over freshly baked bread.', N'pizza24.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (25, 3, N'Cream of Mushroom Soup', 4.9, N'A hearty bowl of rich mushroom soup.', N'pizza25.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (26, 3, N'Onion Rings', 8.9, N'Crispy fried onion rings.', N'pizza26.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (27, 3, N'Crispy Fries', 7.9, N'Golden fried potato fries.', N'pizza27.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (28, 3, N'Chicken Pops', 12, N'Juicy bites fried to perfection.', N'pizza28.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (29, 3, N'Cheesy Flatbread', 7.9, N'Flatbread baked with mozzarella cheese.', N'pizza29.jpg')
INSERT INTO [dbo].[Items] ([ItemID], [CatID], [FoodName], [FoodPrice], [About], [ItemImage]) VALUES (30, 3, N'Sausage Bites', 9.9, N'Crunchy pan-fried chicken salami wrapped in fresh dough for the perfect savoury bite.', N'pizza30.jpg')
SET IDENTITY_INSERT [dbo].[Items] OFF
